version: '3'

services:
  web:
  #DO NOT USE THIS IMAGE PLZ
    image: msfthackcr.azurecr.io/surveyfrontent:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:80 